version: "3.8"

networks:
  micro-net:
    driver: bridge

services:
  hazelcast1:
    image: hazelcast/hazelcast:5.3
    container_name: hz1
    networks:
      - micro-net
    ports:
      - "5701:5701"
    environment:
      - HZ_CLUSTERNAME=dev

  hazelcast2:
    image: hazelcast/hazelcast:5.3
    container_name: hz2
    networks:
      - micro-net
    ports:
      - "5702:5701"
    environment:
      - HZ_CLUSTERNAME=dev

  hazelcast3:
    image: hazelcast/hazelcast:5.3
    container_name: hz3
    networks:
      - micro-net
    ports:
      - "5703:5701"
    environment:
      - HZ_CLUSTERNAME=dev

  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages_db
    ports:
      - "5432:5432"
    networks:
      - micro-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  config-server:
    build:
      context: ./config-server
    container_name: config_server
    networks:
      - micro-net
    ports:
      - "8080:8000"

  logging-service-1:
    build:
      context: .
      dockerfile: ./logging-service/Dockerfile
    container_name: ls1
    environment:
      - HZ_NODES=hz1:5701,hz2:5701,hz3:5701
      - CONFIG_SERVER=http://config-server:8000
      - ADVERTISED_URL=http://ls1:8000
    networks:
      - micro-net
    depends_on:
      - hazelcast1
      - config-server

  logging-service-2:
    build:
      context: .
      dockerfile: ./logging-service/Dockerfile
    container_name: ls2
    environment:
      - HZ_NODES=hz1:5701,hz2:5701,hz3:5701
      - CONFIG_SERVER=http://config-server:8000
      - ADVERTISED_URL=http://ls2:8000
    networks:
      - micro-net
    depends_on:
      - hazelcast2
      - config-server

  logging-service-3:
    build:
      context: .
      dockerfile: ./logging-service/Dockerfile
    container_name: ls3
    environment:
      - HZ_NODES=hz1:5701,hz2:5701,hz3:5701
      - CONFIG_SERVER=http://config-server:8000
      - ADVERTISED_URL=http://ls3:8000
    networks:
      - micro-net
    depends_on:
      - hazelcast3
      - config-server

  counter-service:
    build:
      context: .
      dockerfile: ./counter-service/Dockerfile
    container_name: cs
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=messages_db
      - HZ_NODES=hz1:5701,hz2:5701,hz3:5701
      - CONFIG_SERVER=http://config-server:8000
      - ADVERTISED_URL=http://cs:8000
    networks:
      - micro-net
    depends_on:
      - postgres
      - config-server

  facade-service:
    build:
      context: .
      dockerfile: ./facade-service/Dockerfile
    container_name: fs
    ports:
      - "8000:8000"
    environment:
      - CONFIG_SERVER=http://config-server:8000
      - HZ_NODES=hz1:5701,hz2:5701,hz3:5701
    networks:
      - micro-net
    depends_on:
      - config-server

volumes:
  pgdata:
