# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"\'\n\nLogRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x01(\t2\x8e\x01\n\x0eLoggingService\x12\x39\n\nLogMessage\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\"\x00\x12\x41\n\x0bGetMessages\x12\x15.logging.EmptyRequest\x1a\x19.logging.MessagesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=65
  _globals['_LOGRESPONSE']._serialized_start=67
  _globals['_LOGRESPONSE']._serialized_end=96
  _globals['_EMPTYREQUEST']._serialized_start=98
  _globals['_EMPTYREQUEST']._serialized_end=112
  _globals['_MESSAGESRESPONSE']._serialized_start=114
  _globals['_MESSAGESRESPONSE']._serialized_end=150
  _globals['_LOGGINGSERVICE']._serialized_start=153
  _globals['_LOGGINGSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
