# DB credentials kept in a Secret (separate from ConfigMap so they can be RBAC'd).
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: apz-lab5
type: Opaque
stringData:
  DB_USER: user
  DB_PASSWORD: password
